# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    bourse.collection_data_provider:
        class: 'AppBundle\DataProvider\BourseCollectionDataProvider'
        public: false
        tags:
            -  { name: 'api_platform.', priority: 2 }

    bourse.item_data_provider:
        class: 'AppBundle\DataProvider\BourseItemDataProvider'
        public: false
        tags:
            -  { name: 'api_platform.item_data_provider' }
